### ISSUE TITLE
I have an question regarding velocity

### ISSUE THREAD

**Issue by Cyrusbye720** [cometcake575/Origami-Paper#2]
How to bind with port if I'm running velocity software?? I mean i tried creating many allocation of my paper server but I'm unable to bind port of velocity of that allocation port do you understand what I mean??

**Comment by cometcake575** [comment]
I'm not sure what you mean

**Comment by Cyrusbye720** [comment]
In simple words how will I get the ip of origami server??

**Comment by Cyrusbye720** [comment]
Is it with port allocation things??

**Comment by cometcake575** [comment]
If you're setting up a server on Origami, the port is set up in the same way as a regular server, you configure it in the server.properties iirc
